services:
  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11435:11434"
    networks:
      - ollama-net

  api:
    build: .
    ports:
      - "8005:8005"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11435
    depends_on:
      - ollama
    networks:
      - ollama-net

volumes:
  ollama:

networks:
  ollama-net:
    driver: bridge